# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/realme/RMX1911/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX1911

PRODUCT_COPY_FILES += \
    vendor/realme/RMX1911/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/realme/RMX1911/proprietary/etc/cne/Nexus/ATT/ATT_profiles.xml:system/etc/cne/Nexus/ATT/ATT_profiles.xml \
    vendor/realme/RMX1911/proprietary/etc/cne/Nexus/ROW/ROW_profiles.xml:system/etc/cne/Nexus/ROW/ROW_profiles.xml \
    vendor/realme/RMX1911/proprietary/etc/cne/Nexus/VZW/VZW_profiles.xml:system/etc/cne/Nexus/VZW/VZW_profiles.xml \
    vendor/realme/RMX1911/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/realme/RMX1911/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/realme/RMX1911/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/realme/RMX1911/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
#    vendor/realme/RMX1911/proprietary/lib/libbtconfigstore.so:system/lib/libbtconfigstore.so \
    vendor/realme/RMX1911/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/realme/RMX1911/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/realme/RMX1911/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/realme/RMX1911/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/realme/RMX1911/proprietary/lib/libstagefright_softomx.so:system/lib/libstagefright_softomx.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdaac.so:system/lib/libwfdaac.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdclient.so:system/lib/libwfdclient.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdmmsrc_system.so:system/lib/libwfdmmsrc_system.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdsinksm.so:system/lib/libwfdsinksm.so \
    vendor/realme/RMX1911/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/realme/RMX1911/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/realme/RMX1911/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/realme/RMX1911/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/realme/RMX1911/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/realme/RMX1911/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.oppo.hardware.ktv@1.0.so:system/lib/vendor.oppo.hardware.ktv@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/realme/RMX1911/proprietary/lib64/libbtconfigstore.so:system/lib64/libbtconfigstore.so \
    vendor/realme/RMX1911/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/realme/RMX1911/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/realme/RMX1911/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/realme/RMX1911/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdclient.so:system/lib64/libwfdclient.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdcommonutils.so:system/lib64/libwfdcommonutils.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdconfigutils.so:system/lib64/libwfdconfigutils.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdmminterface.so:system/lib64/libwfdmminterface.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdmmsink.so:system/lib64/libwfdmmsink.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdrtsp.so:system/lib64/libwfdrtsp.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdsinksm.so:system/lib64/libwfdsinksm.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfdsm.so:system/lib64/libwfdsm.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfduibcinterface.so:system/lib64/libwfduibcinterface.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfduibcsink.so:system/lib64/libwfduibcsink.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfduibcsinkinterface.so:system/lib64/libwfduibcsinkinterface.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfduibcsrc.so:system/lib64/libwfduibcsrc.so \
    vendor/realme/RMX1911/proprietary/lib64/libwfduibcsrcinterface.so:system/lib64/libwfduibcsrcinterface.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.oppo.hardware.ktv@1.0.so:system/lib64/vendor.oppo.hardware.ktv@1.0.so \
    vendor/realme/RMX1911/proprietary/product/bin/dpmd:system/bin/dpmd \
    vendor/realme/RMX1911/proprietary/product/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/realme/RMX1911/proprietary/product/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:system/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/realme/RMX1911/proprietary/product/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/realme/RMX1911/proprietary/product/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qualcomm.qti.imscmservice-V2.2-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.2-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qualcomm.qti.uceservice-V2.0-java.jar:system/framework/com.qualcomm.qti.uceservice-V2.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.qualcomm.qti.uceservice-V2.1-java.jar:system/framework/com.qualcomm.qti.uceservice-V2.1-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/realme/RMX1911/proprietary/product/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/realme/RMX1911/proprietary/product/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.cne.internal.api-V1.0-java.jar:system/framework/vendor.qti.hardware.data.cne.internal.api-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.cne.internal.constants-V1.0-java.jar:system/framework/vendor.qti.hardware.data.cne.internal.constants-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.connection-V1.0-java.jar:system/framework/vendor.qti.hardware.data.connection-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.connection-V1.1-java.jar:system/framework/vendor.qti.hardware.data.connection-V1.1-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar:system/framework/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.iwlan-V1.0-java.jar:system/framework/vendor.qti.hardware.data.iwlan-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.ims.callinfo-V1.0-java.jar:system/framework/vendor.qti.ims.callinfo-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar:system/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/product/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/realme/RMX1911/proprietary/product/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/realme/RMX1911/proprietary/product/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/realme/RMX1911/proprietary/product/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/realme/RMX1911/proprietary/product/lib/libsdm-disp-apis.qti.so:system/lib/libsdm-disp-apis.qti.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.display.color@1.1.so:system/lib/vendor.display.color@1.1.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.display.color@1.2.so:system/lib/vendor.display.color@1.2.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.display.color@1.3.so:system/lib/vendor.display.color@1.3.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.qti.hardware.perf@2.0.so:system/lib/vendor.qti.hardware.perf@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib/vendor.qti.hardware.wifidisplaysession@1.0.so:system/lib/vendor.qti.hardware.wifidisplaysession@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.imscmservice@2.0.so:system/lib64/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.imscmservice@2.1.so:system/lib64/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.imscmservice@2.2.so:system/lib64/com.qualcomm.qti.imscmservice@2.2.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.uceservice@2.0.so:system/lib64/com.qualcomm.qti.uceservice@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.qualcomm.qti.uceservice@2.1.so:system/lib64/com.qualcomm.qti.uceservice@2.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.quicinc.cne.api@1.0.so:system/lib64/com.quicinc.cne.api@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.quicinc.cne.api@1.1.so:system/lib64/com.quicinc.cne.api@1.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.quicinc.cne.constants@1.0.so:system/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.quicinc.cne.constants@2.0.so:system/lib64/com.quicinc.cne.constants@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/com.quicinc.cne.constants@2.1.so:system/lib64/com.quicinc.cne.constants@2.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/realme/RMX1911/proprietary/product/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/realme/RMX1911/proprietary/product/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/realme/RMX1911/proprietary/product/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/realme/RMX1911/proprietary/product/lib64/libsdm-disp-apis.qti.so:system/lib64/libsdm-disp-apis.qti.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.display.color@1.1.so:system/lib64/vendor.display.color@1.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.display.color@1.2.so:system/lib64/vendor.display.color@1.2.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.display.color@1.3.so:system/lib64/vendor.display.color@1.3.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.api@1.0.so:system/lib64/vendor.qti.hardware.data.cne.internal.api@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.constants@1.0.so:system/lib64/vendor.qti.hardware.data.cne.internal.constants@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.cne.internal.server@1.0.so:system/lib64/vendor.qti.hardware.data.cne.internal.server@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.connection@1.0.so:system/lib64/vendor.qti.hardware.data.connection@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.connection@1.1.so:system/lib64/vendor.qti.hardware.data.connection@1.1.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so:system/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.iwlan@1.0.so:system/lib64/vendor.qti.hardware.data.iwlan@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.data.qmi@1.0.so:system/lib64/vendor.qti.hardware.data.qmi@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.iop@2.0.so:system/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.perf@2.0.so:system/lib64/vendor.qti.hardware.perf@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.hardware.wifidisplaysession@1.0.so:system/lib64/vendor.qti.hardware.wifidisplaysession@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.ims.callinfo@1.0.so:system/lib64/vendor.qti.ims.callinfo@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.ims.rcsconfig@1.0.so:system/lib64/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.imsrtpservice@2.0.so:system/lib64/vendor.qti.imsrtpservice@2.0.so \
    vendor/realme/RMX1911/proprietary/product/lib64/vendor.qti.imsrtpservice@2.1.so:system/lib64/vendor.qti.imsrtpservice@2.1.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.btconfigstore@1.0.so:system/lib/vendor.qti.hardware.btconfigstore@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.btconfigstore@1.0.so:system/lib64/vendor.qti.hardware.btconfigstore@1.0.so

PRODUCT_PACKAGES += \
    WfdService \
    libantradio \
    QtiTelephonyService \
    TimeService \
    uceShimService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    WfdCommon

